# Where should we write the GIF?
Output demo.gif

# Set up a 1200x600 terminal with 46px font.
Set FontFamily "Fira Code"
Set FontSize 21
Set Width 1500
Set Height 900
Set Shell zsh
#Set Theme "Dracula"

Set Theme {"name":"Breeze","black":"#31363b","red":"#ed1515","green":"#11d116","yellow":"#f67400","blue":"#1d99f3","magenta":"#9b59b6","cyan":"#1abc9c","white":"#eff0f1","brightBlack":"#7f8c8d","brightRed":"#c0392b","brightGreen":"#1cdc9a","brightYellow":"#fdbc4b","brightBlue":"#3daee9","brightMagenta":"#8e44ad","brightCyan":"#16a085","brightWhite":"#fcfcfc","background":"#232627","foreground":"#eff0f1" }

# Type a command in the terminal.
Type "./alpha_tui load examples/programs/stack.alpha"

# Pause for dramatic effect...
Sleep 1s

# Run the command by pressing enter.
Enter

Sleep 500ms

Type "s"

Sleep 500ms

Type "n"

Sleep 500ms

Type "n"

Sleep 500ms

Type "n"

Sleep 500ms

Type "n"

Sleep 500ms

Type "n"

Sleep 500ms

Type "n"

Sleep 500ms

Type "n"

Sleep 500ms

Type "n"

Sleep 500ms

Type "n"

Sleep 500ms

Type "n"

Sleep 500ms

Type "n"

Sleep 500ms

Type "n"

Sleep 500ms

Type "n"

Sleep 500ms

Type "n"

Sleep 500ms

Type "n"

Sleep 500ms

Type "n"

Sleep 500ms

Type "n"

Sleep 500ms

Type "n"

Sleep 500ms

Type "n"

Sleep 500ms

Type "n"

Sleep 500ms

Type "n"

Sleep 500ms

Type "n"

Sleep 500ms

Type "n"

Sleep 500ms

Type "n"

Sleep 500ms

Type "n"

# Admire the output for a bit.
Sleep 3s

# Start another run

Type "q"

Sleep 500ms

Type "./alpha_tui load examples/programs/faculty.alpha"

Sleep 1s

Enter

Sleep 500ms

Type "d"

Sleep 500ms

Up

Sleep 500ms

Up

Sleep 500ms

Up

Sleep 500ms

Up

Sleep 500ms

Up

Sleep 500ms

Up

Sleep 500ms

Type "b"

Sleep 500ms

Up

Sleep 500ms

Up

Sleep 500ms

Up

Sleep 500ms

Up

Sleep 500ms

Type "b"

Sleep 500ms

Up

Sleep 500ms

Up

Sleep 500ms

Up

Sleep 500ms

Up

Sleep 500ms

Up

Sleep 500ms

Type "b"

Sleep 500ms

Type "d"

Sleep 500ms

Type "s"

Sleep 500ms

Type "r"

Sleep 500ms

Type "r"

Sleep 500ms

Type "r"

Sleep 500ms

Type "r"

Sleep 500ms

Type "r"

Sleep 500ms

Type "r"

Sleep 500ms

Type "r"

Sleep 500ms

Type "r"

Sleep 500ms

Type "r"

Sleep 500ms

Type "r"

Sleep 500ms

Type "r"

Sleep 500ms

Type "r"

Sleep 500ms

Type "r"

Sleep 500ms

Type "r"

Sleep 500ms

Type "r"

Sleep 500ms

Type "r"

Sleep 500ms

Type "r"

Sleep 500ms

Type "r"

Sleep 500ms

Type "r"

Sleep 500ms

Type "r"

Sleep 3s
